// <auto-generated />
using System;
using AHKFlowApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AHKFlowApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502225527_Phase3HotkeyRebuild")]
    partial class Phase3HotkeyRebuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.Hotkey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<bool>("Alt")
                        .HasColumnType("bit");

                    b.Property<bool>("AppliesToAllProfiles")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Ctrl")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("OwnerOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("Shift")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Win")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OwnerOid");

                    b.HasIndex("OwnerOid", "Key", "Ctrl", "Alt", "Shift", "Win")
                        .IsUnique()
                        .HasDatabaseName("IX_Hotkey_Owner_Modifiers");

                    b.ToTable("Hotkeys");
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.HotkeyProfile", b =>
                {
                    b.Property<Guid>("HotkeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HotkeyId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("HotkeyProfiles");
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.Hotstring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AppliesToAllProfiles")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsEndingCharacterRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTriggerInsideWord")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Replacement")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerOid");

                    b.HasIndex("OwnerOid", "Trigger")
                        .IsUnique()
                        .HasDatabaseName("IX_Hotstring_Owner_Trigger");

                    b.ToTable("Hotstrings");
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.HotstringProfile", b =>
                {
                    b.Property<Guid>("HotstringId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HotstringId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("HotstringProfiles");
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FooterTemplate")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("HeaderTemplate")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OwnerOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerOid");

                    b.HasIndex("OwnerOid", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("IX_Profile_Owner_DefaultOnly")
                        .HasFilter("[IsDefault] = 1");

                    b.HasIndex("OwnerOid", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Profile_Owner_Name");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.TestMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TestMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Message = "hello test record"
                        });
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("OwnerOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("bit");

                    b.Property<int>("RowsPerPage")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OwnerOid");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.HotkeyProfile", b =>
                {
                    b.HasOne("AHKFlowApp.Domain.Entities.Hotkey", null)
                        .WithMany("Profiles")
                        .HasForeignKey("HotkeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AHKFlowApp.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.HotstringProfile", b =>
                {
                    b.HasOne("AHKFlowApp.Domain.Entities.Hotstring", null)
                        .WithMany("Profiles")
                        .HasForeignKey("HotstringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AHKFlowApp.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.Hotkey", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("AHKFlowApp.Domain.Entities.Hotstring", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
