#Requires -Version 5.1
<#
.SYNOPSIS
    Allocates a free localhost port pair, patches frontend/API dev config, writes a per-worktree manifest, and prints the dotnet run commands needed to start the API + UI for this worktree.

.DESCRIPTION
    Configure-only - does not start dotnet processes. Run it once per worktree before you `dotnet run`. The first worktree on the machine lands on 5600/5601; subsequent worktrees step +2/+2 to the next free pair.

.PARAMETER ApiPort
    Force a specific API port. If the port is in use the launcher errors out (no fallback).

.PARAMETER UiPort
    Force a specific UI port. If omitted but -ApiPort is given, UiPort defaults to ApiPort + 1.

.EXAMPLE
    .\start-local-stack.ps1

.EXAMPLE
    .\start-local-stack.ps1 -ApiPort 5610 -UiPort 5611
#>
[CmdletBinding()]
param(
    [int] $ApiPort,
    [int] $UiPort
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\Common.ps1"

$RepoRoot = Split-Path $PSScriptRoot -Parent
$FrontendSettings = Join-Path $RepoRoot 'src/Frontend/AHKFlowApp.UI.Blazor/wwwroot/appsettings.Development.json'
$BackendSettings = Join-Path $RepoRoot 'src/Backend/AHKFlowApp.API/appsettings.Development.json'
$ManifestPath = Join-Path $PSScriptRoot '.env.local'
$LockPath = Join-Path $env:TEMP 'ahkflow-port-alloc.lock'

function Test-PortFree([int] $Port) {
    $listener = $null
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        return $true
    } catch {
        return $false
    } finally {
        if ($listener) {
            $listener.Stop()
        }
    }
}

function Find-FreePair([int] $StartApi = 5600, [int] $EndApi = 5698) {
    for ($api = $StartApi; $api -le $EndApi; $api += 2) {
        $ui = $api + 1
        if ((Test-PortFree -Port $api) -and (Test-PortFree -Port $ui)) {
            return @{ Api = $api; Ui = $ui }
        }
    }
    throw "No free port pair found in $StartApi-$($EndApi + 1)."
}

function Update-FrontendBaseAddress([string] $Path, [string] $NewBaseAddress) {
    if (Test-Path $Path) {
        $json = Get-Content $Path -Raw | ConvertFrom-Json
        if (-not $json.PSObject.Properties['ApiHttpClient']) {
            $json | Add-Member -NotePropertyName ApiHttpClient -NotePropertyValue ([pscustomobject]@{ BaseAddress = $NewBaseAddress })
        } elseif (-not $json.ApiHttpClient) {
            $json.ApiHttpClient = [pscustomobject]@{ BaseAddress = $NewBaseAddress }
        } else {
            $json.ApiHttpClient | Add-Member -NotePropertyName BaseAddress -NotePropertyValue $NewBaseAddress -Force
        }
    } else {
        Write-Warn "Frontend appsettings.Development.json not found - writing ApiHttpClient only."
        Write-Warn "Run scripts/setup-dev-entra.ps1 to populate the AzureAd section before starting the UI."
        $json = [pscustomobject]@{
            ApiHttpClient = [pscustomobject]@{ BaseAddress = $NewBaseAddress }
        }
    }
    $json | ConvertTo-Json -Depth 10 | Set-Content -Path $Path -Encoding UTF8
}

function Update-BackendCorsAllowedOrigin([string] $Path, [string] $AllowedOrigin) {
    if (Test-Path $Path) {
        $json = Get-Content $Path -Raw | ConvertFrom-Json
    } else {
        Write-Warn "Backend appsettings.Development.json not found - writing Cors only."
        $json = [pscustomobject]@{}
    }

    if (-not $json.PSObject.Properties['Cors']) {
        $json | Add-Member -NotePropertyName Cors -NotePropertyValue ([pscustomobject]@{})
    } elseif (-not $json.Cors) {
        $json.Cors = [pscustomobject]@{}
    }

    $json.Cors | Add-Member -NotePropertyName AllowedOrigins -NotePropertyValue @($AllowedOrigin) -Force
    $json | ConvertTo-Json -Depth 10 | Set-Content -Path $Path -Encoding UTF8
}

function Write-Manifest([string] $Path, [int] $ApiPort, [int] $UiPort, [string] $WorktreePath) {
    $content = @(
        "# Generated by scripts/start-local-stack.ps1 - do not commit",
        "AHKFLOW_API_URL=http://localhost:$ApiPort",
        "AHKFLOW_UI_URL=http://localhost:$UiPort",
        "AHKFLOW_API_PORT=$ApiPort",
        "AHKFLOW_UI_PORT=$UiPort",
        "AHKFLOW_WORKTREE_PATH=$WorktreePath"
    ) -join "`r`n"
    Set-Content -Path $Path -Value $content -Encoding UTF8
}

# Acquire machine-wide allocation lock. FileMode.CreateNew fails atomically if the file already exists.
$lockHandle = $null
$attempt = 0
while ($attempt -lt 50) {
    try {
        $lockHandle = [System.IO.File]::Open($LockPath, [System.IO.FileMode]::CreateNew, [System.IO.FileAccess]::Write, [System.IO.FileShare]::None)
        break
    } catch {
        $attempt++
        Start-Sleep -Milliseconds 100
    }
}
if (-not $lockHandle) {
    throw "Could not acquire allocation lock at $LockPath after 5 seconds. If no other launcher is running, delete the file manually."
}

try {
    Write-Step 'Allocating port pair'

    if ($ApiPort) {
        if (-not $UiPort) { $UiPort = $ApiPort + 1 }
        if (-not (Test-PortFree -Port $ApiPort)) { throw "Requested API port $ApiPort is in use." }
        if (-not (Test-PortFree -Port $UiPort)) { throw "Requested UI port $UiPort is in use." }
        Write-Success "$ApiPort/$UiPort free (explicit)"
        $pair = @{ Api = $ApiPort; Ui = $UiPort }
    } else {
        $pair = Find-FreePair
        Write-Success "$($pair.Api)/$($pair.Ui) free"
    }

    Write-Step 'Configuring frontend'
    Update-FrontendBaseAddress -Path $FrontendSettings -NewBaseAddress "http://localhost:$($pair.Api)"
    Write-Success $FrontendSettings

    Write-Step 'Configuring API CORS'
    Update-BackendCorsAllowedOrigin -Path $BackendSettings -AllowedOrigin "http://localhost:$($pair.Ui)"
    Write-Success $BackendSettings

    Write-Step 'Writing manifest'
    Write-Manifest -Path $ManifestPath -ApiPort $pair.Api -UiPort $pair.Ui -WorktreePath $RepoRoot
    Write-Success $ManifestPath
} finally {
    if ($lockHandle) {
        $lockHandle.Close()
        $lockHandle.Dispose()
        Remove-Item $LockPath -ErrorAction SilentlyContinue
    }
}

Write-Host ""
Write-Host "Run these in two terminals:" -ForegroundColor Cyan
Write-Host ""
Write-Host "  dotnet run --project src/Backend/AHKFlowApp.API --launch-profile `"Docker SQL (Recommended)`" -- --urls `"http://localhost:$($pair.Api)`""
Write-Host ""
Write-Host "  dotnet run --project src/Frontend/AHKFlowApp.UI.Blazor --launch-profile `"http`" -- --urls `"http://localhost:$($pair.Ui)`""
Write-Host ""
Write-Host "API:  http://localhost:$($pair.Api)" -ForegroundColor Green
Write-Host "UI:   http://localhost:$($pair.Ui)" -ForegroundColor Green
